mode: train_cbm
seed: 2
dataset_name: AWA2
dataset_params:
  batch_size: 64
  workers: 2
  return_concepts: true
  data_dir: /home/dani00003/GUIDE-cbm-WIP/data/AwA2
model_name: Standard_AWA2
paths:
  default_root_dir: ./experiments/
  metric_dir: ./last_metrics/
  DAG_file: ./data/AwA2/adjacency_v1.csv
  input_model_path: ./experiments/AWA2/train_backbone/Standard_AWA2/blackbox_configs/blackbox_awa2/lightning_logs/version_0/checkpoints/epoch=49-step=17500.ckpt
hyperparameters_model2:
  num_classes: 50
  num_exogenous: 390
  num_side_channel: 50
  num_concepts: 85
  masking_algorithm: zuko
  num_hidden_layers_in_maskedmlp: 0
  previous_model_output_size: 512
  last_layer_mask: true
  concept_representation: soft
  side_dropout: true
  dropout_prob: 0.8
hyperparameters:
  learning_rate: 0.0001
  lambda_weight: 1
  frozen_model1: true
trainer_param:
  max_epochs: 100
