mode: train_c2y
seed: 42
dataset_name: AWA2
dataset_params:
  batch_size: 256
  workers: 2
  return_labels: true
  return_images: false
model_name: "c2y"
paths:
  default_root_dir: "./experiments/"
  metric_dir: "./last_metrics/"
hyperparameters:
  num_classes: 50
  num_concepts: 85
  learning_rate: 0.0001
  linear_classifier: true
trainer_param:
  max_epochs: 100
