mode: train_x2y
seed: [42,7,1,134,89]
dataset_name: AWA2
dataset_params:
  batch_size: 64
  workers: 2
  return_concepts: false
  data_dir: /home/dani00003/GUIDE-cbm-WIP/data/AwA2

model_name: Standard_CUB
paths:
  default_root_dir: ./experiments/
  metric_dir: ./last_metrics/
hyperparameters:
  num_classes: 50
  learning_rate: 0.0001
  frozen: false
trainer_param:
  max_epochs: 50
