mode: train_cbm
seed: 42
seeds:
- 42
- 7
- 1
- 134
- 89
dataset_name: CelebA
experiment_name: graph_ensemble_consensus_dynamic_medium_ep300_lam1_5_both
loss_type: both
dataset_params:
  batch_size: 256
  workers: 2
  return_labels: true
  return_images: true
  class_name: unfair
backbone_model: Standard_CelebA
multi_expert:
  num_experts: 5
  noise_type: consensus
  noise_level: medium
  consensus: 0.9
dynamic_graphs:
  enabled: true
  p_base: 0.15
  p_private: 0.05
  refresh_every: 10
hyperparameters_model2:
  num_classes: 1
  num_concepts: 7
  num_exogenous: 512
  num_side_channel: 5
  concept_representation: group_soft
  num_hidden_layers_in_maskedmlp: 0
  previous_model_output_size: 512
  side_dropout: true
  dropout_prob: 0.9
  use_alpha: true
  alpha_l1_weight: 0.0001
hyperparameters:
  learning_rate: 0.001
  lambda_weight: 1.5
  frozen_model1: true
trainer_param:
  max_epochs: 300
paths:
  default_root_dir: ./experiments/
  DAG_file: ./data/CelebA/final_DAG_unfair.csv
  expert_graphs_dir: ./data/CelebA/expert_graphs/consensus/medium/
  input_model_path: ./pretrained_models/CelebA/version_11/checkpoints/epoch=89-step=6840.ckpt
