mode: train_cbm
seed: [42,7,1,134,89]
dataset_name: AWA2
dataset_params:
  batch_size: 64
  workers: 2
  return_concepts: true
  data_dir: /home/dani00003/GUIDE-cbm-WIP/data/AwA2
model_name: Standard_CUB
paths:
  default_root_dir: ./experiments/
  metric_dir: ./last_metrics/
  DAG_file: ./data/AwA2/adjacency_v1.csv
  input_model_path: ./pretrained_models/AWA2/version_0/checkpoints/best.ckpt
hyperparameters_model2:
  num_classes: 50
  num_exogenous: 512
  num_concepts: 85
  num_side_channel: 0
  masking_algorithm: none
  last_layer_mask: false
  concept_representation: soft
hyperparameters:
  learning_rate: 0.0001
  lambda_weight: 1
  frozen_model1: true
trainer_param:
  max_epochs: 100
